### ISSUE TITLE
KA-Lite server does not start on boot after option selected post installation

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite-installers#106]
OS : XP 
Browser : Chrome 
Version : 0.14 Development Installer

After installation during which the option to start on boot was not selected, enabling the option after installation does not have the expected affect of having the server start after a reboot of the system. The screen shot after rebooting shows the browser on 120.0.0.1:8008 after waiting and refreshing for several minutes, also no python processes have started.
![2015-07-22_8-41-56](https://cloud.githubusercontent.com/assets/4349806/8828800/3c969980-3051-11e5-8a13-c5c49e7ccfbf.png)

**Comment by EdDixon** [comment]
Also confirmed on XP that during installation selecting the option to start the server on system startup still fails as well. Retitled the issue to include both use cases.

**Comment by MCGallaspy** [comment]
So neither selecting the run-at-boot option during installation or after installation works on Windows XP? Do you experience this issue on other versions of Windows?

**Comment by EdDixon** [comment]
@mike some how I think this one got lost in the mix :) best that I can recall it affected all version windows versions but keep at least one brain surgery in mind since then :) it does still exist on XP in 0.15.0 will check the others soon!

**Comment by MCGallaspy** [comment]
Okay, I'll take a stab at it.

**Comment by MCGallaspy** [comment]
I was not able to replicate this on Windows 7 using 0.15.1 -- @radinamatic can we work together to try this out? @EdDixon thanks for your original report.

Some additional notes to myself after investigating this a bit:
* The scheduled task runs as the SYSTEM user -- and so creates a `.kalite` directory in the systemprofile dir. Could be a problem if the user e.g. runs KA Lite as themselves first, then restarts and the scheduled task runs KA Lite as SYSTEM. It could make it appear that data was lost, when in fact two different `.kalite` directories have been created.
* In KA Lite 0.15.x, the user is prompted to restart the computer after installation, but currently for 0.16.x the user is no longer prompted to restart.
* One approach would be to set a KALITE_USER, like what @benjaoming does on linux -- but then we must support *moving* data for users who are upgrading. *Where* the user's `.kalite` directory is depends on whether they're using the optional start-at-boot feature. Also as pointed out above, it's possible for the user to have two or more `.kalite` dirs if they run KA Lite as different users and/or using the start-at-boot feature.
* The location of relevant data is also different depending on whether the user is running 0.12.x, 0.13.x, or 0.14.x :( -- it's a complicated upgrade scenario.

**Comment by benjaoming** [comment]
> One approach would be to set a KALITE_USER, like what @benjaoming does on linux

Just to clarify this, it's not an env var: It works by putting the username of the default ka lite user in `/etc/ka-lite/userrname`.

**Comment by MCGallaspy** [comment]
@radinamatic can you verify that the "Start at boot" option doesn't work on Windows XP for 0.16.x, and also see if it fails to work on other versions of Windows? You can grab an installer from our build server (ask in hipchat). It may be that the process is slow-running, which could make it appear that it didn't work. Check to see if there is the characteristic python process (owned by SYSTEM in this case).

Secondly, if it indeed doesn't work we should try to establish why -- ping me and I'll help with that.

**Comment by radinamatic** [comment]
Confirmed on Windows 7 -  "Start at boot" option doesn't work despite being selected during the installation. No python processes whatsoever.

Only one error message during the installation, which, however apparently manages to finish:

![secret_key](https://cloud.githubusercontent.com/assets/1457929/11842191/4ddbe216-a402-11e5-878b-d6139ac3fcd6.png)

Two error messages appear when I try to start KA Lite from the desktop shortcut:
![config](https://cloud.githubusercontent.com/assets/1457929/11842145/0f1ff0a8-a402-11e5-9eae-e89cbb462a56.png)
![option](https://cloud.githubusercontent.com/assets/1457929/11842151/1866e8ce-a402-11e5-80b9-ad06907719de.png)

Both errors alerts appear twice (1st, 2nd, 1st, 2nd), but after that KA Lite starts, and I'm able to start the server correctly.

**Comment by radinamatic** [comment]
"Start at boot" fails on XP too. Same as for W7, no python processes at all after restart.
Will do W8 next.

**Comment by radinamatic** [comment]
All of the above from installer in Bamboo build # 81.

**Comment by radinamatic** [comment]
(One of my own machines with XP - not VirtualBox)

Another 0.16 installation on Win XP fails to setup the start on boot, but this time there is a visible error:

![boot](https://cloud.githubusercontent.com/assets/1457929/11846763/4afa9ca0-a41a-11e5-8034-8e33e3709ea7.png)

**Comment by radinamatic** [comment]
However, once the installation finished and I tried to activate "Start at boot" - it was not possible. 

![boot2](https://cloud.githubusercontent.com/assets/1457929/11846900/129c316a-a41b-11e5-9547-b0096ea27ee7.png)

In fact, the only option that can be activated from the pic above is the third one ("Auto-start server when KA Lite is run). The other two are unresponsive.

**Comment by radinamatic** [comment]
Second test on W7 (clean VM) fails also, with the same "Failed to create config file/option" alerts.

Server runs OK, creates admin, etc...

**Comment by radinamatic** [comment]
Same fail with W8 (clean VM).
"Failed to create config file/option" alerts from above present too, but server runs OK after closing those, so it's possible to create admin, login, etc... 

So far, this has been confirmed on Win XP/7/8.
How do you suggest we proceed in solving this, @MCGallaspy?

**Comment by radinamatic** [comment]
As the last resort I activated the other two options: "Run KA Lite when the user logs in" and "Auto-start server when KA Lite is run" (the second one was already active, but not working after previous restarts), and restarted the machine. 

The first one worked - KA Lite run at startup, but the third one did not - no Python processes can be seen in the Task Manager.

**Comment by MCGallaspy** [comment]
A few comments, and a basic outline of how I would approach this. @radinamatic you can attempt further debugging if you want, otherwise I'll get to it when I have the opportunity.

1. The error you mention in this comment is entirely new to me: https://github.com/learningequality/installers/issues/106#issuecomment-165111035
    Let's open a new issue for that.
2. The installer attempts to create a scheduled task to start KA Lite, using a script included in the ka-lite repo: https://github.com/learningequality/ka-lite/blob/0.16.x/scripts/add_systemstart_task.bat
    If the scheduled task isn't being created, we should try to determine why.
3. If the scheduled task is successfully created, but KA Lite doesn't start, we have to determine why. You can view the scheduled task through built-in Windows tools, and check whether it ran "succesfully" (which doesn't mean that KA Lite started successfully, since that starts in a new process, but rather that the script ended without errors). There are two possibilities:
    1. The script failed to run -- this has happened in the past, but I don't think that's the case here. You can view whether the script failed to run using the scheduled task viewer. If it did fail, we determine the error by running the script by hand and observing the output.
    2. Second possibility is that the script succeeds, but the KA Lite process fails to start the server. A little more tricky to debug. We can alter the script command and/or redirect KA Lite output to try to determine why it fails to start.

**Comment by MCGallaspy** [comment]
> The script failed to run -- this has happened in the past, but I don't think that's the case here. You can view whether the script failed to run using the scheduled task viewer. If it did fail, we determine the error by running the script by hand and observing the output.

It's this. The included script in the ka-lite repo is out of date.

**Comment by radinamatic** [comment]
#320 opened for the `Error reading secret key file [Errno 21]`

**Comment by radinamatic** [comment]
Or were the "Failed to create config file/option" alerts the ones you wanted a separate issue opened? @MCGallaspy

**Comment by radinamatic** [comment]
With installer # 87, scheduled task is created, and it did not fail (reports as "Success"), however KA Lite process does not start at system restart... :(

So it may be the time for option 3.ii?

**Comment by radinamatic** [comment]
I'm picking up this in the meantime @MCGallaspy, trying to check if start on boot is not selected during the installation, weather it can be properly setup from KA Lite options.

**Comment by radinamatic** [comment]
We should add a sentence specifying that the startup options can be changed from `KA Lite.exe` options. I suggest these changes in the startup options installer window:

```
Choose one of the following options for server startup:

- Run the server at **W**indows startup
- Run the server when this user logs in
- Do not run server at Windows startup

You can change this anytime from the KA Lite Options in the Taskbar notification area.
```
(**W**indows capital letter in the first option)

**Comment by radinamatic** [comment]
Did you change something with `KA Lite.exe` default options? It starts the server automatically when opening from the desktop shortcut?

(screenshot coming)

It seems that now all 3 KA Lite options are activated by default, even though I selected not to run server at startup. 

(screenshot coming)

I would say that running desktop shortcut in this case should only open KA Lite in the Taskbar notification area, not run the server automaticaly.

**Comment by radinamatic** [comment]
Even if I uncheck all 3 options and exit KA Lite, when I start it through the desktop shortcut, it starts again with all 3 options activated.

**Comment by radinamatic** [comment]
Another suggestion would be to reflect the options from the installer in the options inside KA Lite in the Taskbar notification area, to try to minimize confusion between "server" and "KA Lite":

- Run the server when the user logs in
- Run the server at system startup
- Auto-start server when KA Lite is run

**Comment by elvistek** [comment]
I have installed ka lite v 0.15.1 on a raspberry pi and gone through the process as expressed in [http://ka-lite.readthedocs.org/en/0.15.x/installguide/install_all.html#raspberry-pi ](url) but teh server will not start when the pi is booted. What can the problem be? 

I had some problems during installation but running `kalite manage setup` fully completed the installation and i can connect other devices to the server but i have to run the server manually after start up. Any help? as automatic startup of server will be my ideal situation for deployment.

**Comment by benjaoming** [comment]
@elvistek I hope you've solved your problem in the meantime.. but this thread is for a Windows issue :)

You should run this command `sudo echo "pi" > /etc/ka-lite/username` and try running the server again, as the command line output says, you have configured your system to use some user account "tekdgyg" as the default user for KA Lite, I suspect that's your issue...

**Comment by benjaoming** [comment]
@EdDixon has hinted that some of the very very old bat scripts might have worked and some sort of regression has been introduced when moving functionality into the installer:

>  For example selecting the start on boot option will work with newer WIndows systems but fails on XP as the server will not start with that option selected when the machine first boots WIndows XP. This example does not affect WIndows 7 or higher operating systems.

**Comment by benjaoming** [comment]
Also https://github.com/learningequality/installers/pull/322#issuecomment-169119018 :

> I'm disabling the start at boot option from the task tray program on XP. Shortly I'll remove the option from the installer.

**Comment by radinamatic** [comment]
Wow, this issue was a nightmare to debug back then... :imp: 

I can't test in XP anymore, but in Win 7 it's possible to make KA Lite run on startup, though with a convoluted workaround. For some reason I never understood, all three options in the task tray contextual menu start by being activated by default upon install, and even if the user unchecks them, they are going to be there upon reboot. However, even though they all are checked, KA Lite does not start on boot (or when user logs in)! Annoying... :unamused:

The only way to make it run on boot is to:
1. Uncheck the `Run KA Lite at system startup` option.
2. Confirm in the deletion of the scheduled task in the `cmd.exe` window.
3. Immediately **re-check** the `Run KA Lite at system startup` option.
4. Confirm in the creation of the scheduled task in the `cmd.exe` window by inputting the current user password.
5. Reboot and enjoy KA Lite running on system start!

This does not apply on `KA Lite.exe` task tray program that you will still have to start manually from the desktop shortcut. All this works with the current (0.16.7) release, I just re-tested it.

My money is on some weird Windows user permission issue... 

@arceduardvincent @amodia

**Comment by benjaoming** [comment]
@mrpau-dev following up on Radina's more thorough input on this issue, would you be able to make improvements to this? Maybe in by prioritizing in this order: Windows 10, 8, 7.

We could even skip XP since at this point running KA Lite on XP may already require some kind of DIY/technical skill :)

**Comment by radinamatic** [comment]
I would much rather see the balloon notifications enabled again in XP, then the start-on-boot option (since there is a workaround for it).

**Comment by EdDixon** [comment]
Ah, the good old days :) assuming there are no objections, closing.

**Comment by benjaoming** [comment]
Greetings @EdDixon :wave: :heart_eyes:
