### ISSUE TITLE
Kill existing pyrun activity when resetting the kalite-monitor app.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/ka-lite-installers#125]
**Branch**: `master`(osx installer).
**Expected behavior**: Must kill the existing `pyrun` activity when resetting the kalite-monitor app.
**Current behavior**: `pyrun` is not kill when resetting the  kalite-monitor app.

**_Steps to reproduce:**_
1. Run the Kalite-monitor.
2. Start the kalite server.
3. Quit the kalite-monitor app.
4. Open the activity monitor.
5. Search 'py' 

![screen shot 2015-08-07 at 3 25 56 pm](https://cloud.githubusercontent.com/assets/8663934/9130828/a49adf40-3d18-11e5-911c-7cce080f8703.png)

**Comment by benjaoming** [comment]
Hmm, wondering if we should open an issue regarding PEX and then list the currently open pypy issues in the new issue as requirements for the new PEX build? @cpauya @aronasorman

**Comment by cpauya** [comment]
That's a good idea @benjaoming - @mrpau-richard will open an issue re use of PEX.

**Comment by mrpau-richard** [comment]
@benjaoming I created an issue regarding on PEX https://github.com/learningequality/ka-lite/issues/5274

**Comment by mrpau-richard** [comment]
Fixed in [429](https://github.com/learningequality/ka-lite-installers/pull/429)
