### ISSUE TITLE
Cannot start server if port 8008 is used.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite-installers#131]
**Branch** 0.15.x

**Target** master

**Expected Behavior** The app must warn the user that the server cannot start because port 8008 is used by another process.

**Current Behavior** When the "Start KA Lite" menu is clicked, there is no indicator or message that the server cannot start because port 8008 is used.  The user then is left guessing what is going on with the app.

When debugging under Xcode, the console log shows:

```
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

Port 8008 is occupied. Please close the process that is using it.
```

**Screenshots**
- Xcode output when "Start KA Lite" menu is clicked.
  ![screenshot 2015-08-12 23 27 39](https://cloud.githubusercontent.com/assets/175580/9228333/99852b02-414a-11e5-97f7-8933491ffe94.png)
- System menu of the "KA-Lite Monitor" app after "Start KA Lite" menu is clicked.
  ![screenshot 2015-08-12 23 29 44](https://cloud.githubusercontent.com/assets/175580/9228325/941eb12e-414a-11e5-96aa-13aab153efef.png)

**Possible Solution/s** 
1. Check if port 8008 is used and inform the user of such.
2. Show the output of the `kalite` executable when attempting to start the server.  This will inform the user that an error was encountered by the app.  To be addressed by #129.
3. Document the process that the user must manually close the process/app that is using port 8008.

**Related Issue/s**
- [Kill existing pyrun activity when resetting the kalite-monitor app.](https://github.com/learningequality/installers/issues/125)
- [OSX application performance issues.](https://github.com/learningequality/installers/issues/129)

**Comment by MCGallaspy** [comment]
There's a similar problem in Windows with the task-tray icon.
