### ISSUE TITLE
Create a release script for docker, implement it on Bamboo

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite-installers#149]
- [ ] Release script @benjaoming
- [ ] Bamboo implementation @aronasorman

**Comment by benjaoming** [comment]
@aronasorman could you say if there's any environments or options that could/should be passed directly from Bamboo to the docker script? For instance branch name? Or should I just statically implement this for the develop branch?

**Comment by aronasorman** [comment]
We can pass environment variables when the docker script is invoked, I believe.

**Comment by MCGallaspy** [comment]
@benjaoming can we do this within three weeks?

**Comment by benjaoming** [comment]
Well, I actually would vote no at the moment. I need at least 1-2 other people to be familiar with the manual process before automating it. Maybe we can go through this together during our joint 0.16 release sessions? Like say you release a beta.

**Comment by benjaoming** [comment]
We have moved to BuildKite, closing this until it becomes a priority again. I don't have issues building source packages and uploading locally, since this is the only Workflow that makes sense when fixing issues in the Debian installer. We don't need lots of automated builds for Debian, because development pace of KA Lite has slowed down.
