### ISSUE TITLE
 i18n support for installer

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite-installers#168]
**Branch:** master

**Expected Behaviour:** Able to support i18n in our installer.

**Current Behaviour:** The current  installer built doesn't support  i18n.

**Comment by benjaoming** [comment]
This will be fine, but the Kolibri installer should probably have i18n.

Created https://github.com/learningequality/kolibri-installer-osx/issues/1

CC: @mrpau-eduard @mrpau-richard @cpauya
