### ISSUE TITLE
OSX installer - suboptimal user experience (and not working?)

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite-installers#272]
Had a guest to the offices today excited to try out KA Lite, who downloaded the OSX installer and installed. There were numerous issues, ranging from "annoying" to "confusing" to "it didn't work at all". We were never successful in getting it up and running. I'll list a few things here, but it seems like what we need is a serious UX (and testing) sprint on the OSX installer/monitor, as it's currently in pretty a bad state, and likely losing us users (as well as potential supporters).
- Still called "KA-Lite-Monitor" rather than "KA Lite"
- After launching the app, there was no way to know that it was accessible via the task tray icon, or what the next steps should be.
- The preferences window came up at some point, but it was very very confusing (even for me, and I know how it's supposed to work).
  - The "Admin name/password" form looked like it was for putting in the system password. No indication that it was for creating a superuser for use within KA Lite. Also, we don't need that now, since creating the superuser happens in the web interface.
  - Pressing "Apply" did nothing. It was unclear whether it had created a user, or done anything at all -- nothing changed. Window stayed open, and only options were still "Apply" and "Cancel".
  - Going to the second tab, we were just faced with a wall of text full of scary warnings. "Setup: this may delete all your data", etc. Pressing "setup" didn't seem to do anything, and didn't have any progress indicator or other feedback.
  - The KA Lite logo in the bottom left of the window had a spinner/progress icon on it, but it was frozen/not spinning.

![image](https://cloud.githubusercontent.com/assets/618416/11201489/8d5f2456-8c93-11e5-8f7a-b2b977fc8204.png)
- We could not figure out how to get the server started. The options under the task tray dropdown were all grayed out, except Preferences. No apparent way to start the server. We eventually gave up.

OSX version was not El Capitan. Will request more details.

@jtamiace, perhaps you or an intern could help with trying this process out and making UX recommendations? A lot of low-hanging fruit, so it doesn't need to be an expert UX analyst.

(CC @aronasorman @cpauya)

Thanks!

**Comment by cpauya** [comment]
Hi @jamalex,

So sorry to hear that the OSX app did not work with your guest, I assume it was v0.15.x?

With those issues, it's most likely that an error has occurred in the .app (or ka-lite) thus it did not work as expected, these may be visible in the `Logs` tab.

Some answers to your queries:

1. We have already removed the "monitor" on the `develop` branch (for 0.16.x release).
2. The .app have [notifications](https://support.apple.com/en-us/HT204079) to notify the user of things like: "KA-Lite is starting...", "Setup is finished!  You can now start KA-Lite.", etc.  Perhaps the system was on "Do Not Disturb" mode?
3. Regarding the Preferences window:

    1. We have already removed the form for creating the admin username/password on the `develop` branch (for 0.16.x release).
    1. When the `Apply` button was clicked, were there any messages on the `Logs` tab?
    1. We have already removed the setup, extract assessment, and reset app in our `feature/osx-0.16.x` branch (due for 0.16.x).
    1. We will remove the confusing spinner icon.

For tracing any issues about the .app:

1. On the `Terminal`, try typing `kalite` to see if it was installed.  If not, then something went wrong during the setup of ka-lite which happens on initial launch of the .app.
1. We can check output messages of the .app at the `Logs` tab.
1. We can also use the `Console` application at the `/Applications/Utilities` of the OSX machine, and filtering by "KA-Lite".

Yes, more details would be very helpful like which KA-Lite installer and OSX version were used.

Again, I apologise if the installer/.app did not work for you, something must have happened that we didn't catch on our tests.  I admit that the .app needs a lot of UX attention and would really appreciate if someone could jump in to help out.

**Comment by benjaoming** [comment]
@cpauya -- I could identify this as a possibly fixed / possibly remaining issue?

> We will remove the confusing spinner icon.

Otherwise, this could be closed? :)

**Comment by benjaoming** [comment]
Closing this because of missing feedback - if we have to work out these issues, we would need to chunk them up into separate workable smaller issues.

CC: @mrpau-eduard @mrpau-richard @cpauya

**Comment by cpauya** [comment]
A lot has happened to the Application UI and functionality since this issue was reported.

So yes @benjaoming, let's close this and open specific issues as they emerge.
