### ISSUE TITLE
Windows uninstaller should remove all unneeded associated registry entries on uninstall

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite-installers#29]
Discovered MUI registry remnants after a full uninstall and deletion of the KA-lite program and installation folder. Attached is the ccleaner finding of MUI's associated with the program I think we should be removing unless they are required and not recreated during an upgrade as many of the files and folders are for that specific purpose
![screenshot from 2015-04-24 18 52 28](https://cloud.githubusercontent.com/assets/4349806/7330983/f0b35968-eab9-11e4-9bca-150a9e283639.png)
.

**Comment by mrpau-richard** [comment]
Hi @EdDixon I can't reproduce this issue in 0.17 KA Lite windows installer. I'm closing this.
