### ISSUE TITLE
Windows Installer python version check foiled if Python 3 is also installed

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite-installers#296]
On Windows 10 and without the python 2.7.10 path set in the windows but with python 2.7.10 installed, an installation of 0.15.1 will error with the following error messages should the user choose to answer no knowing python is installed just not in path. The default option for the 2.7.10 python installer is not to add itself to the path string but it is optional to include that. Additionally KA-Lite can be installed without that if the user sets a specific environent variable for kalite to the required path (KALITE_PYTHON). We should not force the user to install a redundant copy of python on the system potentially causing confusion as to which python path to follow for KA-Lite and other applications. Screenshots of the related message dialogs attached. 
![2015-12-02_13-17-39](https://cloud.githubusercontent.com/assets/4349806/11543969/ade68b40-98fc-11e5-8222-fce5f21e7f52.png)
![2015-12-02_13-30-59](https://cloud.githubusercontent.com/assets/4349806/11543973/b41624da-98fc-11e5-9444-81df3762c870.png)
![2015-12-02_13-31-19](https://cloud.githubusercontent.com/assets/4349806/11543976/b8db4054-98fc-11e5-820b-baca3396d958.png)

**Comment by MCGallaspy** [comment]
Did you verify as you claim that having python in the path does not cause
this issue?

**Comment by EdDixon** [comment]
No I have not as that would take time and as I understand it this is for eminent release without much testing planned, however another potential bug has now appeared. During replication of it I will add the python path to the path string here during this test going on now to verify that both replicate. (I hope not)

**Comment by EdDixon** [comment]
@MCGallaspy verifying now that with python in the environment path this is in deed not an issue as I have claimed.

**Comment by MCGallaspy** [comment]
Do you also have python 3 installed?

**Comment by EdDixon** [comment]
Python 3 is installed on this live development machine along with 2.7.10 from the previous KA Lite installation of version 0.15.0 which I was upgrading and is apparently a factor leading to the error. In a clean WIndows 10 VM upgrade test and with no other versions of Python installed, I am not prompted to rerun the python installer while only python 2.7.10 is installed from the previous 15.0 installation. Also on the development machine there is no specified python version added to the path but pathing for KA-Lite is handled by KALITE_PYTHON env var which may also have been a factor.

**Comment by MCGallaspy** [comment]
>  In a clean WIndows 10 VM upgrade test and with no other versions of Python installed, I am not prompted to rerun the python installer

That's also my observation.

> Yes, Python 3 is installed

I think that's the real issue here.

**Comment by MCGallaspy** [comment]
I tried installing Python 2.7 followed by Python 3.5 on Windows 7. I wasn't able to replicate this issue. However, all signs point to python 3 being installed as foiling the version check done by the installer.

**Comment by EdDixon** [comment]
@MCGallaspy it could be possible that the KALITE_PYTHON env var being set prior to the upgrade attempt caused the error I guess? That's what I get for testing on a production machine LOL sorry to create the confusion but I am surprised to see any runtime error regardless of what else may have been running or installed during the 0.15.1 installation attempt. My installation did apparently "take" despite the error and is still in this stat. Starting the server does work and opens the admin creation screen on 0.15.1 but I backed out at that point in case there is any more information it may provide. If so just let me know it does appear to be working regardless?

**Comment by MCGallaspy** [comment]
> it could be possible that the KALITE_PYTHON env var being set prior to the upgrade attempt caused the error I guess?

It is possible -- what was the value of `KALITE_PYTHON` when you attempted this?

**Comment by EdDixon** [comment]
c:\Python27\python.exe 

Which is the installed path of my python 2.7 version?

**Comment by MCGallaspy** [comment]
@radinamatic can we add this to the pipeline as well? The goal would be to try to replicate ed's original error. I believe it could be done by installing python 3 and python 2 before installing KA Lite.

**Comment by radinamatic** [comment]
Sure thing, will test too! @MCGallaspy

**Comment by radinamatic** [comment]
Just to make sure: I should install Python 2.7 and 3.5 prior to installing KA Lite to test this issue?
Do I need to mess with the env vars too?
@MCGallaspy

**Comment by EdDixon** [comment]
Because it did not replicate on Mikes windows 7 test I feel you may need to have those same env vars set to replicate the error. May be best to make a snapshot prior and test both ways I guess... Welcome to my world :)

**Comment by MCGallaspy** [comment]
@radinamatic the python version is checked here during installation: https://github.com/learningequality/installers/blob/develop/windows/installer-source/KaliteSetupScript.iss#L348

It's possible that different env variables could produce different results. I wouldn't expect KALITE_PYTHON to affect the above check, it's simply not used there. It may be affected by the value of PATH, but I doubt it. The thing to look into is how Windows decides which program to run when you type it into the run console. I notice the following behavior on my own system:

1. If I type "python" into a cmd.exe prompt, it starts a Python 3.4 interpreter (from Anaconda). This is determined by PATH.
2. If I type (Windows Key)+R to open the run console and enter "python" there, it opens a different Python 2.7 interpreter. I don't know how this is determined.

My guess is that the above LOC searches for an appropriate executable using the same rules as #2, and that in @EdDixon's case it finds Python 3 (or another version).

**Comment by MCGallaspy** [comment]
> I should install Python 2.7 and 3.5 prior to installing KA Lite to test this issue?

And yes, that's how I would attempt to replicate this. I would also try installing 2.7 and 3.x in different orders. I also wouldn't begin messing with env vars unless I couldn't replicate it this way first, in order to narrow down the possible causes of this bug.

**Comment by radinamatic** [comment]
Both Python installers give the option "Add to path" but it's unchecked by default, so I'm unsure if people do that at all, and secondly, if I should do it for purpose of this test... :confused: 
@MCGallaspy

**Comment by radinamatic** [comment]
Windows 8.1 (fresh VM):
Installing Python 2.7 and then 3.5 (neither of them added in path) defaults to using `c:\Python27\python.exe` with the RuntimeWarning in console window, but no errors as @EdDixon reported. 

I'll revert to snapshot prior to installing 3.5 and add it to path to see if that changes something.

**Comment by radinamatic** [comment]
Windows 8.1:

Restored the screenshot and installed Python 3.5 with the **path check box activated** and than proceeded with KA Lite installation. Couldn't replicate the error by @EdDixon, as no error messages during Python 2.7 and KA Lite installation appeared, but server was not starting.

`KALITE_SCRIPT_DIR` was `C:\Python27\Scripts`, but user PATH variable was `
C:\Users\IEUser\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\IEUser\AppData\Local\Programs\Python\Python35-32\` (no Python in system `Path` variable)

Once I changed the user PATH variable to `C:\Python27\Scripts;C:\Python27\` server managed to start.

So, this is potentially a problem for users who have Python 3 installed and its env var set up prior to installing KA Lite, since the option to setup the Python 2.7 in path is at the bottom of all the components in the installer window and the chances are that the user is not going to see it. Could we maybe add the alert in the KA Lite installation prior to triggering the Python 2.7 installer?  

.

**Comment by mrpau-richard** [comment]
@radinamatic I think it's not an issue either the user installed python 3.5 because the KA Lite application will use the KALITE_SCRIPT_DIR environment as variable python path.

I also tested that installing python 3.5 and python 2.7 will not having any issue as @EdDixon reported.

**Comment by radinamatic** [comment]
Way to dig ghosts from the past... :smile: 

I installed Python 3.6.1 and added its env var to path, *prior* to installing KA Lite. Server is running OK, as `KALITE_SCRIPT_DIR` and `KALITE_PYTHON` must be doing their work.

![win8 1 start running - oracle vm virtualbox_310](https://user-images.githubusercontent.com/1457929/27928973-7ee384e6-6291-11e7-8ffa-e6093f6c992c.png)

Closing this as not extant on latest release
