### ISSUE TITLE
Stop the server running in background prior to upgrade

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite-installers#351]
Stop the server running in background prior to upgrade to 0.16
##### Upgrade scenario

0.13 through 0.15 > 0.16 on W7 (build # 114)
##### Current Behavior

In KA Lite versions 0.13 through 0.15 users had the option to run the server on system startup with the scheduled task. Since that task was run as the SYSTEM user, current user of KA Lite is not even able to stop the server. During the upgrade process, server is still running background and that is a potential problem for two reasons:
1. Could be causing the issue #347 - [error described here](https://github.com/learningequality/installers/pull/335#issuecomment-171485593). We haven't been able to reproduce it reliably, but could be still related to the server running in the background during upgrade.
2. Bad user experience: Once the upgrade process is finished, the old scheduled task is deleted, but server is still running (1-2 python processes are active) and current user cannot stop it. User is also unable to start the server on their own since task tray program registers the server that is running and displays only the `Stop Server` option as available, but it cannot stop the python process run as SYSTEM user. Task-tray program also displays the `Load in browser` option as available, but if user selects it, it will only open a blank page at server's IP. 

At this point user is left with the only option of restarting the system to regain control of the KA Lite server. We could include that requirement in the installer, or even better: stop the server prior to starting the upgrade process. 
##### Steps to reproduce
1. Install 0.15.1.
2. Upgrade to 0.16.
3. Start KA Lite.exe.
4. Activate "Load in browser" in KA Lite task-tray Options.

**Comment by mrpau-richard** [comment]
Fixed in #439

**Comment by benjaoming** [comment]
Reopening since #439 hasn't been merged or released.
