### ISSUE TITLE
Antivirus software may auto-quarantine KA Lite.exe on Windows installer

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite-installers#372]
## Summary

Had some trouble getting KA Lite installed on Windows 10, specifically because Bitdefender (antivirus software) thought KA Lite.exe was a threat. It was only after disabling it (thanks @MCGallaspy ) that I was able to install.
## Branch or installer
- Installer: Windows 
- Version: 0.16 
## Screenshots

![windows 0-16 installer](https://cloud.githubusercontent.com/assets/6668144/13620825/82fc9180-e547-11e5-8055-6e50c1d0cff7.JPG)

![antivirus](https://cloud.githubusercontent.com/assets/6668144/13620827/8810e5ae-e547-11e5-856a-52577e053470.png)
## How to reproduce
1. Have some antivirus software active (I used Bitdefender - free edition)
2. Install KA Lite 0.16 on Windows 10

**Comment by benjaoming** [comment]
I wonder what file it tries to copy/move that triggers the antivirus to block it...

Other than that, if people are running anti-virus, I guess they should also be aware that it may cause problems during installation of software?

Unless we know that we're doing something we shouldn't I think we shouldn't spend too much time on this...

**Comment by benjaoming** [comment]
Neds more information and tests with other anti-virus programs...

**Comment by mrpau-richard** [comment]
I tested the kalite 0.16 windows installer downloaded at [pantry](http://pantry.learningequality.org/downloads/ka-lite/0.16/installers/windows/KALiteSetup-0.16.0.exe) and the antivirus did not detect the kalite executable in auto-quarantine during the installation.
I used these ativirus to try to reproduce this issue:
Bitdefender free edition.
Windows 10 64 bit.
![screen shot 2017-11-14 at 5 35 34 pm](https://user-images.githubusercontent.com/8663934/32774723-28826ee4-c968-11e7-8c20-e400f98ba2b0.png)

Windows 7 32 bit.
![screen shot 2017-11-14 at 5 09 49 pm](https://user-images.githubusercontent.com/8663934/32774745-3bc9c4ca-c968-11e7-8b99-07540cfdba57.png)


Avast antivirus.
Windows 10 64 bit.
![screen shot 2017-11-14 at 6 06 13 pm](https://user-images.githubusercontent.com/8663934/32774792-6bec3804-c968-11e7-923d-a591c2d59192.png)

**Comment by benjaoming** [comment]
@mrpau-richard that's nice!

Can you re-produce the issue with an unsigned installer?

In case not, let's close this and move on :)

**Comment by mrpau-richard** [comment]
@benjaoming I can't even re-produce this issue in the unsigned installer.
I think with the updated version of antivirus this issue can't be reproduced.
![screen shot 2017-11-15 at 3 59 37 pm](https://user-images.githubusercontent.com/8663934/32825194-fc929ad6-ca1e-11e7-9932-99318b894801.png)

Closing this.

**Comment by benjaoming** [comment]
Yup, sounds good, thanks for looking into this!
