### ISSUE TITLE
Verify if the pkg is corrupted before installing.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/ka-lite-installers#389]
## Summary

`pkg` need to verified before the installation.
## Branch or installer
- Installer: OS X 
- Version: 0.16.2
## Screenshots

Before installation it must check if the pkg is not corrupted.
![screen shot 2016-04-15 at 11 20 22 am](https://cloud.githubusercontent.com/assets/8663934/14550753/18f85cc2-02fe-11e6-96af-7c7bccadf40b.png)

Corrupted pkg will failed during installation.
![screen shot 2016-04-15 at 11 11 13 am](https://cloud.githubusercontent.com/assets/8663934/14550755/229bc9f8-02fe-11e6-9b8c-3ce934b94738.png)

**Comment by cpauya** [comment]
We've experienced this today when we've downloaded the Bamboo builds using our mobile internet.

Run `pkgutil --check-signature ./KA-Lite.pkg` to check a .pkg.

This is the output if the .pkg is NOT corrupted:
```
$ pkgutil --check-signature ./KA-Lite.pkg
Package "KA-Lite.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. Developer ID Installer: Foundation for Learning Equality, Inc. (H83B64B6AV)
       SHA1 fingerprint: D5 8A 4C 0F F0 03 A1 86 D4 8E 63 07 1B 16 B7 71 5D EE 96 FA
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
```
If it emits anything else, like "checksum is invalid" -- means the .pkg downloaded is corrupt.

**Comment by mrpau-eugene** [comment]
@mrpau-richard is this still a valid issue that needs to be fixed?

**Comment by mrpau-richard** [comment]
@mrpau-eugene Yeah, this issue still valid to be fix during the installation of `.pkg` KA Lite mac installer.

**Comment by cpauya** [comment]
I don't understand how this can be implemented at all.  A user will download an installer which will now come in `.dmg` format.  So I'm not sure how this will become an issue now.

@mrpau-richard Can you explain what you want to achieve on this issue?

**Comment by benjaoming** [comment]
As I understand these search results, verification of a .pkg in a .dmg is automatic?

https://encrypted.google.com/search?num=30&hl=en&q=mac+skip+verifying

**Comment by mrpau-richard** [comment]
@cpauya I think this issue can't be reproduced if the .pkg installer is inside the .dmg file. Because if the dmg is corrupted and there's no way we can run the .pkg installer. 

I think this issue is already fixed.

**Comment by benjaoming** [comment]
Let's go with that, and reopen if someone can reproduce with a broken .dmg

If you wanna test it, you can just corrupt the .dmg

https://unix.stackexchange.com/questions/222359/how-to-corrupt-an-archive-file-in-a-controlled-way
