### ISSUE TITLE
Contentpacks exercise images are not properly loaded.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/ka-lite-installers#400]
## Summary

Contentpacks for non-english exercise images are not properly loaded, when another user account of the same machine use KA Lite application and download non-english language contentpacks.
## Branch or installer
- Installer: Windows
- Version: 0.16.5.0
## How to reproduce
1. Install KA Lite in user account A.
2. Create another user account B and log in.
3. On user account B, use existing KA Lite application and install new contentpacks for non-english language.
4. Navigate to an exercise that has an image.

**Screenshot**
![screen shot 2016-06-03 at 10 27 11 pm](https://cloud.githubusercontent.com/assets/8663934/15817456/a52eb8f0-2c0a-11e6-8b2a-0b1b3b1b4e50.png)

Related issue https://github.com/learningequality/ka-lite/issues/5129

**Comment by benjaoming** [comment]
This will be fixed by #424 in case we start using well-known contentpack zip locations because then they will be extracted as user data and not reside in a possibly unreadable shared system dir.

**Comment by benjaoming** [comment]
I'm closing this in favor of moving to a common-for-all-installers approach as mentioned in #438.
