### ISSUE TITLE
Clicking icon to run KA Lite app does not pop up task tray or give feedback that it did something.

### ISSUE THREAD

**Issue by djallado** [learningequality/ka-lite-installers#408]
## Summary

by: @jtamiace
Windows 8.1

"It wasn't until I checked the icon tray after clicking the KA Lite app icon multiple times that I saw that it had done something. Should the icon tray pop up right away since it wasn't too apparent that it had done something to the task tray?"

"There were also as many icons as the number of times that i clicked on the app:"
![multiple](https://cloud.githubusercontent.com/assets/8664071/16168286/a80ee88c-3534-11e6-9dbf-e54d6b420290.png)

Related issue: https://github.com/learningequality/ka-lite/issues/3836
## Branch or installer
- Installer: Windows
- Version: 0.16.x

or:
- Branch: 0.16.x
## Screenshots

![multiple](https://cloud.githubusercontent.com/assets/8664071/16168253/51a1314e-3534-11e6-9ada-eb5da813f743.png)
## How to reproduce
1. Install KA Lite
2. Set so the server does not start on computer start up
3. Restart computer
4. Click app icon for KA Lite

**Comment by radinamatic** [comment]
Fixed in #432, but I can't seem to close issues since the repo name change... 
@aronasorman can I have my perms back? 😛

**Comment by mrpau-richard** [comment]
Fixed in #432, Closing this issue.
