### ISSUE TITLE
Release notes for 0.16.9

### ISSUE THREAD

**Issue by mrpau-eduard** [learningequality/ka-lite-installers#412]
## Summary

Update the release notes for documentation for every fix and new implementation.
## Branch or installer
- Installer: `OSX`
- Branch: `0.16.x`

**Comment by benjaoming** [comment]
Related: #426

**Comment by benjaoming** [comment]
Hi @mrpau-eduard @mrpau-richard is this one something we should close?

**Comment by mrpau-eduard** [comment]
Yeah, It should be clossing it now.
