### ISSUE TITLE
Using built PEX file in KA Lite installers.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/ka-lite-installers#417]
### KA Lite Installers issues.
1. [# 125 - Kill existing pyrun activity when resetting the kalite-monitor app](https://github.com/learningequality/installers/issues/125)
2. [# 98 - Drop Pyrun on OS X Installer and replace it with virtualenv.](https://github.com/learningequality/installers/issues/98)
### KA Lite issues.
1. [#5264 - Downgrading requests causes issues with old versions of pip](https://github.com/learningequality/ka-lite/issues/5264)
2. [#3399 - bin/kalite does not support PyPy](https://github.com/learningequality/ka-lite/issues/3399)
3. [#4315 - "python bin\kalite" should not switch interpreter unless required](https://github.com/learningequality/ka-lite/issues/4315)

/cc @benjaoming @aronasorman

**Comment by benjaoming** [comment]
Since this is merged for the 0.17 pre-releases, maybe we can close this and also have a look at all the related issues?

**Comment by mrpau-richard** [comment]
@benjaoming I agree and I will close it.
