### ISSUE TITLE
OSX installer claims it's 0.16.0 not 0.16.9

### ISSUE THREAD

**Issue by julianharty** [learningequality/ka-lite-installers#426]
## Summary

> The opening screen shows ￼
> version 0.16.0 rather than 0.16.9 
## Version
- Installer: OSX
- Version: 0.16.9
## Traceback or server.log snippet

```
None, and not relevant.
```
## Screenshots

Attached.
## How to reproduce
1. Run KA-Lite-0.16.9.pkg
2. Check the text in the opening screen.
   <img width="617" alt="screen shot 2016-10-04 at 17 21 49" src="https://cloud.githubusercontent.com/assets/785891/19082680/1794c8ee-8a57-11e6-8893-59a77c12ec74.png">

Please can you ensure the version number is consistent in the installer, the app and the installer.

**Comment by cpauya** [comment]
Thanks for reporting this @julianharty

**Comment by benjaoming** [comment]
Yup, can confirmed I've observed this -- possibly for all of the OSX installers. It's only during installation though, but still confusing.

**Comment by benjaoming** [comment]
To avoid similar future blunders, this was fixed in #448 and released in 0.17.1 - thanks @julianharty for reporting this!
