### ISSUE TITLE
KA-lite for mac uninstall and now not allowing clean install

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite-installers#446]
_From @kevhyde on April 7, 2017 4:39_

## Summary

*I am not experienced in programming. I installed KA lite on my mac today and got it working as far as the questions and user accounts etc. I could not show ka lite where my compressed downloaded videos were by scanning. Nothing was being found. I could not see the .kalite folder and tried to show a new data file location in preferences so I could link to torrented video. This stopped my ka lite working. I then deleted the KA-lite folder and contents from applications. Then I found a github page here that gave terminal commands to remove invisible .kalite folders from the system. I've done this. When I try to install the KA-lite again, it goes through the motions of installing but then at summary stage advised that installation failed*

## System information

KA-lite version 0.17

mac OS yosemite 10.10.5
 - Version: 0.17
 - safari

Thanks very much for any suggestions, Kevin

_Copied from original issue: learningequality/ka-lite#5434_

**Comment by benjaoming** [comment]
@kevhyde thanks for reporting this - I've moved it to our installers repository.

I can't tell for sure what can cause the installer to fail, maybe @mrpau-eduard @mrpau-richard can suggest to remove some additional artifacts from the old installation which can block a fresh install?

**Comment by mrpau-eduard** [comment]
Hi @kevhyde you can download this file [ka-lite-remover.sh](https://github.com/learningequality/ka-lite-installers/blob/master/osx/ka-lite-remover.sh) then run it on your machine.
Steps to run this script:
> 1. Download the `ka-lite-remover.sh` from github.
> 2. Open terminal.
> 3. Run `bash ~/path/to/script/ka-lite-remover.sh `

This script will remove all the dependencies of the old KA-Lite installation. 
You need to run this script to remove the `*.plist`, `kalite` executable and the kalite resources.

**Comment by kevhyde** [comment]
Thanks for your help. Sorry but I'm not that experienced in this kind of programming. Can I just double check the process you've outlined above? To download the ka-lite-remove.sh do I just copy and paste the lines of code? Then copy them into terminal?

I just can't see where I can download a script file or something. If you could explain it in real dummies language that would be appreciated as this does look like the fix I"m looking for.

Thanks, Kevin

**Comment by radinamatic** [comment]
Hi @kevhyde!  :slightly_smiling_face: 

1. Right-click (or was it `Option`+ click on Mac?) this link [ka-lite-remover.sh](https://github.com/learningequality/ka-lite-installers/blob/master/osx/ka-lite-remover.sh) and choose `Save (link) as` to download the `ka-lite-remover.sh` script file to, let's say, your **Desktop**.
2. Open Terminal.
3. Type `cd Desktop` and press `Enter`.
4. Type `bash ka-lite-remover.sh ` and press `Enter`.

Let us know what appears in the Terminal after this.

**Comment by benjaoming** [comment]
@mrpau-eduard what needs to be done for the Mac installer automatically perform various steps pf `ka-lite-remover.sh` during uninstallation (except user data)?

**Comment by kevhyde** [comment]
Hi guys, thanks very much for your help. That has@radinamatic that has worked thanks and now I have ka lite installed, have changed my contents folder location and added torrented videos and it's all running. This is a great system of learning that you've been creating here, thanks very much. Kevin

**Comment by radinamatic** [comment]
@kevhyde Glad it helped... 🙂 
Have fun using KA Lite!!!

Cheers!

**Comment by benjaoming** [comment]
Cool, let's keep the issue open until @mrpau-eduard or @mrpau-richard can tell if the Mac Installer uninstallation can be modified easily so this doesn't happen to others ?

**Comment by cpauya** [comment]
Hi @benjaoming - I did a back-read and it seems that Kevin did not do a clean uninstall as we documented at  [Uninstallation of the installed KA Lite package.](https://github.com/learningequality/ka-lite-installers/tree/master/osx#uninstallation-of-the-installed-ka-lite-package).

Here's what he did:

> ...This stopped my ka lite working. I then deleted the KA-lite folder and contents from applications. Then I found a github page here that gave terminal commands to remove invisible .kalite folders from the system. I've done this...

I don't know if the "terminal commands" he mentioned were the ones in `ka-lite-remover.sh`.

The "normal" way to uninstall an app in macOS is to just drag it to the Trash.  However since we did some customizations during setup, we created the `ka-lite-remover.sh` for a clean uninstall and [renamed it as `KA-Lite_Uninstall.tool`](https://github.com/learningequality/ka-lite-installers/blob/master/osx/post_installation.sh#L21) after a successful installation. 

So there's no need to modify the Mac installer and we can just point users to the doc. 

I think we can close this now. 😸

**Comment by kevhyde** [comment]
Hi there, no you’re right. Initially I ran a couple of terminal commands I found in forums that deleted some things but I still couldn’t install ka lite again.

Then I used the ka-lite-remover.sh script you guys suggested and it worked for me and allowed a reinstall without problem.

I think the problem was that I’d deleted the application folder as you’ve suggested and then I couldn’t do a proper uninstall. I’m learning now :)

Thanks, Kevin

**Comment by cpauya** [comment]
Thanks for verifying and I'm glad to hear it's working-out good for you @kevhyde.

I'm closing this now. 😸

**Comment by benjaoming** [comment]
> So there's no need to modify the Mac installer and we can just point users to the doc how to do a clean uninstall.

Just to understand you clearly: If a user drags KA Lite to Trash (the conventional uninstall), will things break or not?

**Comment by benjaoming** [comment]
I can see that it's part of the official docs: http://ka-lite.readthedocs.io/en/develop/installguide/install_all.html#mac-osx  -- strange link, should probably separate the uninstall guides - this for now this *is* the link to the UNinstall :)

**Comment by mrpau-eduard** [comment]
Hi @benjaoming
> Just to understand you clearly: If a user drags KA Lite to Trash (the conventional uninstall), will things break or not?

Yes it is, It will break the uninstallation process. 
Using the `KA-Lite_Uninstall.tool` will do the following:

1. Unset the environment variables: KALITE_PYTHON and KALITE_HOME.
2. Remove the .plist and preferences files, kalite executable and the ka-lite resources.
3. When run stand-alone, it confirms removal of the KA-Lite data directory as specified by the KALITE_HOME env var.

**Comment by mrpau-eduard** [comment]
The installation process for the `Mac OSX` is outdated it should be updated. We will update it. Thank you for noticing it.
