### ISSUE TITLE
•LOCKDOWN = <True or False> (default = False) 

### ISSUE THREAD

**Issue by fhenson1** [learningequality/ka-lite-installers#465]
## Summary

> I want to be able to restrict users from viewing videos unless they are logged in.  I found the LOCKDOWN command.
I made the change in  c:\Users\myname\.kalite\settings.py (2.7.10)

LOCKDOWN = TRUE

and saved the file.

When I try to start kalite it will not start. The python program is not running and will not start.  If I delete 
LOCKDOWN = TRUE
the program starts and runs okay.

Below is the file:

# This is the default location where the kalite command finds its settings
# You can change the below lines to use different default settings or
# you can run kalite <command> --settings=other_module

from kalite.project.settings.base import *

# from kalite.project.settings.dev import *
# from kalite.project.settings.raspberry_pi import *
LOCKDOWN = TRUE
# MY_SETTING = 123

 - Installer: Windows10 - 
Version: 0.17.1

## Traceback or server.log snippet

```

**Comment by mrpau-richard** [comment]
@fhenson1 Try set `True` not all uppercase `TRUE`

`LOCKDOWN = True`

**Comment by fhenson1** [comment]
Richard lower case True worked.

**Comment by fhenson1** [comment]
Thanks for your help.  Lowercase solved the problem.
