### ISSUE TITLE
Drop Pyrun on OS X Installer and replace it with virtualenv.

### ISSUE THREAD

**Issue by djallado** [learningequality/ka-lite-installers#98]
**Branch:** `master (OS X Installer)`

**Expected Behavior:** Download video or update language pack will continue without error.

**Current Behavior:** There's an error when downloading videos or updating language pack.
Here's the screenshoot:

![screen shot 2015-07-15 at 10 38 14 am](https://cloud.githubusercontent.com/assets/8664071/8690003/82f42d4a-2ae1-11e5-9a47-97a95e30c563.png)

**Steps to reproduce:**
1. Login as `Admin User`.
2. Click `Video` tab.
3. Navigate to the `topic tree` and choose your preferred video to download.
4. Click on Download new selected video button. Then error will occur like in the screenshot:
![screen shot 2015-07-15 at 10 38 14 am](https://cloud.githubusercontent.com/assets/8664071/8690083/6f84ea64-2ae2-11e5-9c38-e14f06cd9e1d.png)

**Comment by jamalex** [comment]
@benjaoming Is it possible that the cron server isn't getting passed the correct settings, and hence isn't accessing the shared database (the one migrations should already have been run against)?

**Comment by djallado** [comment]
@aronasorman.

Our plan after dropping `pyrun`:

1. In our script we will check the minimum `python package of 2.7.9+`.
2. If below, then we will prompt the user to to upgrade python.
3. Next is to install offline package `virtualenv`.
4. We will put package `assessmentitems` in `kalite source` 
5. We will include `kalite` source also.
6. Pip packages are included in `.dmg`.

**Comment by benjaoming** [comment]
@jamalex could be a settings discrepancy, but only in case the OSX installer does use a custom settings module. As for the latest `0.14.x` and `develop` branches, they are using the fix for the `--settings` option.

@djallado in case the OSX installer uses one settings module (--settings or DJANGO_SETTINGS_MODULE) for running `kalite manage setup`, then `kalite start` has to use the same and vice versa.

**Comment by cpauya** [comment]
This is a manifestation of the issue on #100 - we can ignore this for now and close this after #100 is closed.

**Comment by cpauya** [comment]
PyRun will still be used for release 0.16.  Moving this to 0.17.

**Comment by benjaoming** [comment]
Is this going to be using PEX?

**Comment by mrpau-richard** [comment]
Fixed in [429](https://github.com/learningequality/ka-lite-installers/pull/429)

**Comment by mrpau-richard** [comment]
@benjaoming Yeah, We're now using PEX in KA Lite OS X installer closing this issue.
